---
- name: Restart stack
  community.docker.docker_compose_v2:
    project_src: "{{ stack_dir }}"
    state: restarted
  environment:
    DOCKER_HOST: "{{ docker_host | default('unix:///var/run/docker.sock') }}"
  listen: "restart_stack"

- name: Restart specific service
  community.docker.docker_compose_v2:
    project_src: "{{ stack_dir }}"
    services:
      - "{{ service_to_restart }}"
    state: restarted
  environment:
    DOCKER_HOST: "{{ docker_host | default('unix:///var/run/docker.sock') }}"
  when: service_to_restart is defined
  listen: "restart_service"

- name: Reload compose configuration
  community.docker.docker_compose_v2:
    project_src: "{{ stack_dir }}"
    state: present
    pull: never
  environment:
    DOCKER_HOST: "{{ docker_host | default('unix:///var/run/docker.sock') }}"
  listen: "reload_compose"
